name: Release image

on:
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract semantic version number
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed 's#^refs/tags/v##')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
